import { Metadata } from 'next';
import {
  LegalList,
  LegalPage,
  LegalSection,
  legalConfig,
} from '@gitroom/frontend/components/legal/legal-page';

export const metadata: Metadata = {
  title: 'Terms of Service | KOLab Social Connectors',
  description:
    'Terms governing use of KOLab Social Connectors for social publishing and messaging.',
};

export default function TermsOfService() {
  return (
    <LegalPage
      title="Terms of Service"
      summary="These terms govern access to KOLab Social Connectors and its social publishing, integration, and messaging capabilities."
    >
      <LegalSection title="1. Agreement">
        <p>
          These Terms of Service (“Terms”) are an agreement between{' '}
          {legalConfig.company} (“KOLab”, “we”, “us”, or “our”) and the person
          or organization using KOLab Social Connectors (“you”). By creating an
          account, connecting a social account, or using the service, you agree
          to these Terms and our Privacy Policy.
        </p>
        <p>
          If you use the service for an organization, you confirm that you have
          authority to accept these Terms and connect the organization’s social
          assets on its behalf. A separate written order, subscription, or
          services agreement may add to these Terms. If it expressly conflicts
          with these Terms, the signed agreement controls for that conflict.
        </p>
      </LegalSection>

      <LegalSection title="2. The service">
        <p>
          KOLab Social Connectors provides tools to connect supported
          third-party platforms, prepare and publish content, synchronize
          account information and analytics, and receive or respond to supported
          business messages and public replies. Features depend on platform
          APIs, permissions, account type, geography, and approval.
        </p>
        <p>
          Threads functionality in the social inbox concerns public replies and
          does not represent a Threads direct-message service. Facebook and
          Instagram responses are subject to platform messaging windows and
          user-initiation requirements.
        </p>
      </LegalSection>

      <LegalSection title="3. Eligibility and accounts">
        <LegalList>
          <li>
            You must be at least 18 and able to enter a binding agreement.
          </li>
          <li>
            Registration and account information must be accurate and kept up to
            date.
          </li>
          <li>
            You are responsible for credentials, authorized users, roles, and
            activity performed through your organization.
          </li>
          <li>
            You must promptly remove users who no longer require access and
            notify us of suspected compromise.
          </li>
          <li>
            You may not share an individual login when separate user accounts
            are available.
          </li>
        </LegalList>
      </LegalSection>

      <LegalSection title="4. Authority to connect social accounts">
        <p>
          You may connect only accounts, Pages, profiles, and business assets
          that you own or are authorized to manage. You authorize KOLab to use
          the permissions and tokens granted through the platform solely to
          provide the requested service, including publishing, synchronization,
          webhook subscription, message retrieval, and responses initiated by
          authorized users.
        </p>
        <p>
          You are responsible for selecting appropriate assets and permissions
          and for ensuring that your organization has a lawful basis to process
          its audience, customer, and message data. KOLab may prevent the same
          external account from being actively connected to conflicting
          organizations unless an approved agency-sharing arrangement applies.
        </p>
      </LegalSection>

      <LegalSection title="5. Your content and instructions">
        <p>
          You retain ownership of content you provide. You grant KOLab a
          limited, non-exclusive right to host, process, reproduce, format,
          transmit, and publish that content as needed to operate the service
          and follow your instructions. This right ends when the content is
          deleted from active systems, except for protected backups and records
          we must retain by law.
        </p>
        <p>
          You are responsible for content, schedules, recipients, links, claims,
          disclosures, approvals, and actions submitted through your account,
          including activity generated by your authorized automations.
        </p>
      </LegalSection>

      <LegalSection title="6. Acceptable use">
        <p>You must not use the service to:</p>
        <LegalList>
          <li>
            violate law, regulation, third-party rights, or platform terms;
          </li>
          <li>
            publish or send unlawful, deceptive, infringing, abusive,
            discriminatory, or malicious content;
          </li>
          <li>
            send spam, evade messaging windows, or contact people without the
            permissions or lawful basis required for that communication;
          </li>
          <li>
            collect, expose, or misuse credentials, tokens, private messages,
            personal data, or confidential information;
          </li>
          <li>
            bypass access controls, rate limits, account limits, moderation, or
            platform enforcement;
          </li>
          <li>
            probe, disrupt, overload, reverse engineer, or introduce harmful
            code into the service, except where law expressly permits limited
            security research;
          </li>
          <li>
            resell or provide the service to unauthorized third parties without
            KOLab’s written permission.
          </li>
        </LegalList>
      </LegalSection>

      <LegalSection title="7. Platform terms and messaging rules">
        <p>
          Your use of Facebook, Instagram, Threads, and every other connected
          service remains governed by that platform’s terms, policies, account
          permissions, and technical limits. You must comply with applicable
          messaging windows, user-consent requirements, content rules, branded
          content disclosures, intellectual-property rules, and community
          standards.
        </p>
        <p>
          KOLab may block, delay, or reject an action when necessary to protect
          the service, comply with a platform response, or avoid an apparent
          policy violation. This does not transfer responsibility for your
          content or communications to KOLab.
        </p>
      </LegalSection>

      <LegalSection title="8. Third-party services">
        <p>
          Social platforms, hosting providers, storage services, payment
          processors, and other integrations are independent third parties.
          Their APIs and availability may change without notice. KOLab does not
          control and is not responsible for their accounts, decisions, outages,
          policy enforcement, data practices, or loss of access.
        </p>
        <p>
          You may need to reconnect an account, grant a revised permission, or
          change a workflow after a platform API or policy change. KOLab cannot
          guarantee publication, delivery, reach, engagement, or continued
          availability of any third-party feature.
        </p>
      </LegalSection>

      <LegalSection title="9. Fees and subscriptions">
        <p>
          Fees, usage limits, billing periods, taxes, and renewal terms are
          stated in the applicable order, plan, or customer agreement. Unless
          that agreement says otherwise, fees are non-refundable once the
          applicable service period begins, except where a refund is required by
          law. We may suspend paid features for overdue undisputed amounts after
          any required notice.
        </p>
      </LegalSection>

      <LegalSection title="10. Privacy and confidential information">
        <p>
          Our Privacy Policy describes KOLab’s handling of personal data. Each
          party must protect the other party’s non-public confidential
          information using reasonable care and use it only for the service
          relationship. These duties do not apply to information that is
          lawfully public, independently developed, or properly received from
          another source without a duty of confidentiality.
        </p>
      </LegalSection>

      <LegalSection title="11. KOLab property and feedback">
        <p>
          KOLab and its licensors retain rights in the service, branding,
          documentation, interfaces, and software, subject to applicable
          open-source licences. No rights are granted except the limited right
          to use the service during the agreement. If you provide feedback, you
          allow KOLab to use it without restriction or payment, provided we do
          not identify you publicly without permission.
        </p>
      </LegalSection>

      <LegalSection title="12. Changes, availability, and beta features">
        <p>
          We may improve, replace, or discontinue features and may perform
          maintenance. We aim to provide a reliable service but do not promise
          uninterrupted operation unless a signed agreement includes a service
          level commitment. Preview or beta features may be changed or removed
          and should not be used for critical workflows unless we agree
          otherwise in writing.
        </p>
      </LegalSection>

      <LegalSection title="13. Suspension and termination">
        <p>
          You may stop using the service and disconnect integrations at any
          time. We may suspend or terminate access when reasonably necessary to
          address a security risk, legal requirement, platform instruction,
          non-payment, material breach, abusive use, or threat to other users or
          the service. Where practical and lawful, we will provide notice and an
          opportunity to remedy the issue.
        </p>
        <p>
          On termination, your right to use the service ends. Provisions that by
          their nature should survive—including payment obligations,
          confidentiality, ownership, disclaimers, liability limits, and dispute
          terms—continue to apply.
        </p>
      </LegalSection>

      <LegalSection title="14. Disclaimers">
        <p>
          To the maximum extent permitted by law, the service is provided “as
          is” and “as available”. KOLab disclaims implied warranties of
          merchantability, fitness for a particular purpose, title, and
          non-infringement. We do not warrant that every post or message will be
          accepted, published, delivered, retained, or displayed by a
          third-party platform.
        </p>
        <p>
          Nothing in these Terms excludes a warranty or right that cannot
          lawfully be excluded.
        </p>
      </LegalSection>

      <LegalSection title="15. Limitation of liability">
        <p>
          To the maximum extent permitted by law, neither party is liable for
          indirect, incidental, special, exemplary, punitive, or consequential
          loss, or for loss of profits, revenue, goodwill, anticipated savings,
          or data, arising from these Terms or the service. KOLab’s aggregate
          liability arising from the service will not exceed the fees paid or
          payable for the service during the twelve months before the event
          giving rise to the claim.
        </p>
        <p>
          These limits do not apply where liability cannot lawfully be limited
          or to fraud, wilful misconduct, or obligations expressly made
          unlimited in a signed agreement.
        </p>
      </LegalSection>

      <LegalSection title="16. Indemnity">
        <p>
          To the extent permitted by law, you will defend and indemnify KOLab
          against third-party claims, damages, and reasonable costs arising from
          your content, your unlawful or unauthorized use of connected accounts,
          your violation of platform rules, or your material breach of these
          Terms. KOLab will give reasonable notice and allow you to control the
          defence, subject to KOLab’s right to participate and to approve any
          settlement that admits fault or imposes obligations on KOLab.
        </p>
      </LegalSection>

      <LegalSection title="17. Governing law and disputes">
        <p>
          These Terms are governed by the laws of Hong Kong, without regard to
          conflict-of-law principles. The courts of Hong Kong have exclusive
          jurisdiction, unless a signed customer agreement provides another
          dispute process or applicable law requires otherwise.
        </p>
      </LegalSection>

      <LegalSection title="18. General terms">
        <p>
          Neither party may assign these Terms without the other’s consent,
          except in connection with a merger, reorganization, sale of
          substantially all relevant assets, or assignment to an affiliate that
          can perform the obligations. If part of these Terms is unenforceable,
          it will be limited to the minimum extent necessary and the remainder
          remains effective. Delay in enforcing a right is not a waiver. These
          Terms and any applicable signed agreement are the complete agreement
          about the service.
        </p>
      </LegalSection>

      <LegalSection title="19. Changes and contact">
        <p>
          We may update these Terms as the service or law changes. We will post
          the revised Terms with an updated date and provide additional notice
          when required. Material changes apply prospectively.
        </p>
        <p>
          Questions may be sent to{' '}
          <a
            className="text-[#f973ff] underline"
            href={`mailto:${legalConfig.email}`}
          >
            {legalConfig.email}
          </a>
          . Notices to KOLab should identify your organization and be addressed
          to {legalConfig.company}, {legalConfig.jurisdiction}.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
